cognitive-complexity-threshold = 10
excessive-nesting-threshold = 4
too-many-arguments-threshold = 4
type-complexity-threshold = 80
too-many-lines-threshold = 80
min-ident-chars-threshold = 2
allowed-idents-below-min-chars = ["..", "id"]
